//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application description page..
        /// </summary>
        internal static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Graph Connect sample for ASP.NET 4.6.
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Graph Connect sample.
        /// </summary>
        internal static string App_Name_Short {
            get {
                return ResourceManager.GetString("App_Name_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caller needs to authenticate..
        /// </summary>
        internal static string Error_AuthChallengeNeeded {
            get {
                return ResourceManager.GetString("Error_AuthChallengeNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        internal static string Error_Introduction {
            get {
                return ResourceManager.GetString("Error_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in .
        /// </summary>
        internal static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get email address.
        /// </summary>
        internal static string Graph_GetEmailAddress_Button {
            get {
                return ResourceManager.GetString("Graph_GetEmailAddress_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get email address.
        /// </summary>
        internal static string Graph_GetEmailAddress_Heading {
            get {
                return ResourceManager.GetString("Graph_GetEmailAddress_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the &lt;b&gt;Get email address&lt;/b&gt; button to get the current user&apos;s email address:.
        /// </summary>
        internal static string Graph_GetEmailAddress_Instruction {
            get {
                return ResourceManager.GetString("Graph_GetEmailAddress_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user&apos;s email address.
        /// </summary>
        internal static string Graph_GetEmailAddress_Results_Label {
            get {
                return ResourceManager.GetString("Graph_GetEmailAddress_Results_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        ///&lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=us-ascii&apos;&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&apos;font-family:calibri&apos;&gt;
        ///&lt;h2&gt;Congratulations!&lt;/h2&gt;
        ///&lt;p&gt;This is a message from the Microsoft Graph Connect Sample. You are well on your way to incorporating Microsoft Graph endpoints in your apps.&lt;/p&gt;
        ///&lt;h3&gt;What&apos;s next?&lt;/h3&gt;&lt;ul&gt;
        ///&lt;li&gt;Check out &lt;a href=&apos;https://graph.microsoft.io&apos;&gt;graph.microsoft.io&lt;/a&gt; to start building Microsoft Graph apps today with all the latest tools, templates, and  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Graph_SendMail_Body_Content {
            get {
                return ResourceManager.GetString("Graph_SendMail_Body_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email.
        /// </summary>
        internal static string Graph_SendMail_Button {
            get {
                return ResourceManager.GetString("Graph_SendMail_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an email.
        /// </summary>
        internal static string Graph_SendMail_Heading {
            get {
                return ResourceManager.GetString("Graph_SendMail_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After you get the email address, optionally change the following fields and then choose the &lt;b&gt;Send email&lt;/b&gt; button:.
        /// </summary>
        internal static string Graph_SendMail_Instruction {
            get {
                return ResourceManager.GetString("Graph_SendMail_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the &lt;b&gt;Get email address&lt;/b&gt; button first..
        /// </summary>
        internal static string Graph_SendMail_Message_GetEmailFirst {
            get {
                return ResourceManager.GetString("Graph_SendMail_Message_GetEmailFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient email addresses, separated by a semicolon.
        /// </summary>
        internal static string Graph_SendMail_Recipients_Label {
            get {
                return ResourceManager.GetString("Graph_SendMail_Recipients_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject of email.
        /// </summary>
        internal static string Graph_SendMail_Subject_Label {
            get {
                return ResourceManager.GetString("Graph_SendMail_Subject_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent from the.
        /// </summary>
        internal static string Graph_SendMail_Subject_Text {
            get {
                return ResourceManager.GetString("Graph_SendMail_Subject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! Your mail was sent..
        /// </summary>
        internal static string Graph_SendMail_Success_Result {
            get {
                return ResourceManager.GetString("Graph_SendMail_Success_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Microsoft.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
    }
}
